spring:
  application:
    name: portfolio-security
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio_jpa?useSSL=false&serveTimezone=UTC
    username: root
    password: 

app:
  jwt:
    # Clave de firma para el algoritmo HS512
    # En http://www.allkeysgenerator.com/ se pueden generar todo tipo de claves
    secret: UkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWnZr4u7x!A%D*F-JaN
    expiration:
      minutes: 525600
  cors:
    allowed-origins: https://portfolio-9d1e3.firebaseapp.com
